### ISSUE TITLE
Class card redeclares typename Card in common.h

### ISSUE THREAD

**Issue by zappybiby** [peter1591/hearthstone-ai#25]
Two lines affected in common.h:  

1. https://github.com/peter1591/hearthstone-ai/blob/master/pilot_run/include/game-engine/cards/common.h#L118 which redeclares https://github.com/peter1591/hearthstone-ai/blob/master/pilot_run/include/game-engine/cards/common.h#L112
and 

2. https://github.com/peter1591/hearthstone-ai/blob/master/pilot_run/include/game-engine/cards/common.h#L161 which redeclares https://github.com/peter1591/hearthstone-ai/blob/master/pilot_run/include/game-engine/cards/common.h#L155

**Comment by peter1591** [comment]
Yup, we should change the name. Feel free to change it and fire a pull request.

**Comment by peter1591** [comment]
archive pilot run issues
