### ISSUE TITLE
Potential Typo

### ISSUE THREAD

**Issue by zappybiby** [peter1591/hearthstone-ai#26]
In [StaticEventTriggerrer.h line 17](https://github.com/peter1591/hearthstone-ai/blob/master/include/Utils/StaticEventTriggerer.h#L17), class 'Invoker' doesn't resolve. Did you mean to use class 'Invoker2'?

**Comment by peter1591** [comment]
It's a templated class, so maybe the compiler resolved it when it scan the source for the first time. So it can be resolved when the templated class got instantiated.

BTW, I use a more clear way to implement this class. See commit 7bccc826 for more detail.
