### ISSUE TITLE
Confused by project structure

### ISSUE THREAD

**Issue by zappybiby** [peter1591/hearthstone-ai#28]
Hello @peter1591, I wanted to ask you about the project structure. So I've been trying to resolve https://github.com/zappybiby/hearthstone-ai/issues/1 but I am not seeing any obvious issues with compiling or anything like that. 

Now I'm wondering if any of the projects you have in the main repo (HearthstoneAI, MCTS, and vs_projects) are linked together in some way. I've never dealt with a repo with multiple projects (and I am new to coding as well) so the structure here confuses me. Maybe we should rename the solutions? Sorry for being a newbie! I hope to add more to this project soon after I get this resolved.

**Comment by peter1591** [comment]
First thing first. The project you're talking about is under the 'pilot_run' folder, Which is, as the name states, is only for a pilot-run. So the folder is not maintained anymore. You should refer to the 'vs_projects' under the root folder for the new one.

The folder structure can be shortly explained as follows.
1. /pilot_run/ui --> this project parse the log, and invoke the AI program /pilot_run/vs2015/MCTS
2. /pilot_run/vs2015/MCTS --> this is the MCTS program written in C++
3. /vs_projects --> this is the on-going projects for game engine and MCTS.

The 'pilot_run' folder can be considered as deprecated. After I finished the new game-engine and MCTS framework, this folder will be removed.
