### ISSUE TITLE
Cannot run using vs 2017

### ISSUE THREAD

**Issue by chengyi** [peter1591/hearthstone-ai#36]
严重性	代码	说明	项目	文件	行	禁止显示状态
错误	CS0103	当前上下文中不存在名称“GameEngineCppWrapper”	GameEngineUI	D:\Code\hearthstone-ai-master\hearthstone-ai-master\vs_projects\GameEngineUI\Form1.cs	32	活动的

**Comment by peter1591** [comment]
Are you using Visual Studio 2017? And try to rebuild all the projects.

**Comment by peter1591** [comment]
Found a possible reason. Fixed in commit 202e5bea.

**Comment by chengyi** [comment]
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0103	The name 'GameEngineCppWrapper' does not exist in the current context	GameEngineUI	D:\Code\hearthstone-ai-master\hearthstone-ai-master\vs_projects\GameEngineUI\Form1.cs	32	Active

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0246	The type or namespace name 'GameEngineCppWrapper' could not be found (are you missing a using directive or an assembly reference?)	GameEngineUI	D:\Code\hearthstone-ai-master\hearthstone-ai-master\vs_projects\GameEngineUI\Form1.cs	34	Active

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0246	The type or namespace name 'GameEngineCppWrapper' could not be found (are you missing a using directive or an assembly reference?)	GameEngineUI	D:\Code\hearthstone-ai-master\hearthstone-ai-master\vs_projects\GameEngineUI\Form1.cs	34	Active

Severity	Code	Description	Project	File	Line	Suppression State
Error (active)	E1696	cannot open source file "Utils/CloneableContainers/Vector.h"	cloneable_containers	d:\Code\hearthstone-ai-master\hearthstone-ai-master\vs_projects\cloneable_containers\Source.cpp	6	
Error (active)	E1696	cannot open source file "Utils/CloneableContainers/PtrVector.h"	cloneable_containers	d:\Code\hearthstone-ai-master\hearthstone-ai-master\vs_projects\cloneable_containers\Source.cpp	7	
Error (active)	E1696	cannot open source file "Utils/CloneableContainers/RemovableVector.h"	cloneable_containers	d:\Code\hearthstone-ai-master\hearthstone-ai-master\vs_projects\cloneable_containers\Source.cpp	8	
Error (active)	E1696	cannot open source file "Utils/CloneableContainers/RemovablePtrVector.h"	cloneable_containers	d:\Code\hearthstone-ai-master\hearthstone-ai-master\vs_projects\cloneable_containers\Source.cpp	9	
Error (active)	E0725	name must be a namespace name	cloneable_containers	d:\Code\hearthstone-ai-master\hearthstone-ai-master\vs_projects\cloneable_containers\Source.cpp	11	
Error (active)	E0276	name followed by '::' must be a class or namespace name	cloneable_containers	d:\Code\hearthstone-ai-master\hearthstone-ai-master\vs_projects\cloneable_containers\Source.cpp	67	
Error (active)	E0029	expected an expression	cloneable_containers	d:\Code\hearthstone-ai-master\hearthstone-ai-master\vs_projects\cloneable_containers\Source.cpp	67	
Error (active)	E0020	identifier "container" is undefined	cloneable_containers	d:\Code\hearthstone-ai-master\hearthstone-ai-master\vs_projects\cloneable_containers\Source.cpp	69	
Warning		The referenced component 'GameEngineCppCLI' could not be found.	GameEngineUI			
Warning		Could not resolve this reference. Could not locate the assembly "GameEngineCppCLI". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.	GameEngineUI			

it still cannot build

**Comment by peter1591** [comment]
Another try to fix that: ca84293b

Can you build the GameEngineCppCLI successfully?

**Comment by chengyi** [comment]
@peter1591 I can't build GameEngineCppCLI 
here is the error log:

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0006	Metadata file 'D:\Code\hearthstone-ai\vs_projects\Debug\GameEngineCppCLI.dll' could not be found	GameEngineUI	D:\Code\hearthstone-ai\vs_projects\GameEngineUI\CSC	1	Active
Warning	LNK4199	/DELAYLOAD:GameEngineCppWrapper.dll ignored; no imports found from GameEngineCppWrapper.dll	GameEngineCppCLI	D:\Code\hearthstone-ai\vs_projects\GameEngineCppCLI\LINK	1	
Error	LNK2028	unresolved token (0A0004B1) "public: int __thiscall GameEngineCppWrapper::GameEngine::Get(void)const " (?Get@GameEngine@GameEngineCppWrapper@@$$FQBEHXZ) referenced in function "public: int __clrcall GameEngineCppWrapper::CLI::GameEngine::Get(void)" (?Get@GameEngine@CLI@GameEngineCppWrapper@@$$FQ$AAMHXZ)	GameEngineCppCLI	D:\Code\hearthstone-ai\vs_projects\GameEngineCppCLI\Source.obj	1	
Error	LNK2019	unresolved external symbol "public: int __thiscall GameEngineCppWrapper::GameEngine::Get(void)const " (?Get@GameEngine@GameEngineCppWrapper@@$$FQBEHXZ) referenced in function "public: int __clrcall GameEngineCppWrapper::CLI::GameEngine::Get(void)" (?Get@GameEngine@CLI@GameEngineCppWrapper@@$$FQ$AAMHXZ)	GameEngineCppCLI	D:\Code\hearthstone-ai\vs_projects\GameEngineCppCLI\Source.obj	1	
Error	LNK1120	2 unresolved externals	GameEngineCppCLI	D:\Code\hearthstone-ai\vs_projects\Debug\GameEngineCppCLI.dll	1

**Comment by peter1591** [comment]
More refinement in e5640361
Maybe related to x86/x64 environment settings.

**Comment by chengyi** [comment]
I can build it, but the ui runs with only a single button in it.
and I can't see any suggestions when I play the hearthstone.

**Comment by peter1591** [comment]
It's still under development... please hold
