### ISSUE TITLE
Request to update ReadMe

### ISSUE THREAD

**Issue by SethKitchen** [peter1591/hearthstone-ai#39]
First I added log.config to C:\Users\[username]\AppData\Local\Blizzard\Hearthstone and added 

[Achievements]
LogLevel=1
FilePrinting=true
ConsolePrinting=true
ScreenPrinting=false

[Power]
LogLevel=1
FilePrinting=true
ConsolePrinting=true
ScreenPrinting=false

If this is needed please add to documentation.

The I follow your directions: Opened C# project under path\hearthstone-ai-master\vs_projects\GameEngineUI

Then I run it. Everything compiles and runs. I see a window with 1 button. I press the button a file picker appears. What do I do?

I see from the code it wants to know where the cpp dll is. I click on it, but then it just pops up with a number (427549). What does this mean? How can I get what the best move is?

**Comment by peter1591** [comment]
The UI part is still under construction.
I will update the readme once it gets finished.

**Comment by SethKitchen** [comment]
It's amazing how many commits you do per week! Any update on how well this is going/when we can start using it?

**Comment by peter1591** [comment]
Sure, will update some progress report later!

**Comment by peter1591** [comment]
folder restructured and readme added
