### ISSUE TITLE
hi, Can U give me a release version for testing? 

### ISSUE THREAD

**Issue by qj739** [peter1591/hearthstone-ai#75]
Please give me a release version with trained  neural nework  , I want to test the win rate of AI VS player. Thank you.

**Comment by peter1591** [comment]
You can refer to the wiki page https://github.com/peter1591/hearthstone-ai/wiki/Train-Default-Policy-Neural-Network to train one for yourself!

**Comment by qj739** [comment]
Can U show me some simulate result(win rate) for the popular deck on the ladder? thank U
