### ISSUE TITLE
Where is tiny_dnn.h

### ISSUE THREAD

**Issue by SethKitchen** [peter1591/hearthstone-ai#76]
I'm trying to follow your train neural network wiki and when i try to do "make" I get ../../src/NeuralNetwork.cpp:14:10: fatal error: tiny_dnn/tiny_dnn.h: No such file or directory
 #include "tiny_dnn/tiny_dnn.h"
          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
Makefile:71: recipe for target '../../src/NeuralNetwork.o' failed
make: *** [../../src/NeuralNetwork.o] Error 1

**Comment by peter1591** [comment]
Please do a git sub module update.
