### ISSUE TITLE
How to Use

### ISSUE THREAD

**Issue by NanoToNano** [peter1591/hearthstone-ai#79]
I use google translation.

I opened /vs_projects/vs_projects.sln using visual studio
Are there any problems with this act?

I got an error

**Comment by NanoToNano** [comment]
Debugging after opening will warn you that you can not find cloneable_containers.exe

**Comment by NanoToNano** [comment]
It seems that he was doing something strange misunderstanding
I do not know startup items

**Comment by peter1591** [comment]
set the startup project to HearthstoneAI, and try again

**Comment by NanoToNano** [comment]
My visual studio can't read the include folder

**Comment by peter1591** [comment]
How do you mean by can’t read?
