### ISSUE TITLE
Reinforcement Learning

### ISSUE THREAD

**Issue by wonderkid27** [peter1591/hearthstone-ai#80]
After we have default policy, why don't we think about reinforcement learning? Training begins with the default policy. At a basic level, this policy is simply played against itself iteratively, updating policy weights according to whether a game was won or lost. One copy of the policy is continually updated and periodically frozen copies of itself are added to the pool of opponents. Do you think it fine?

**Comment by peter1591** [comment]
Yes, totally fine. And of course it's on the road map!

**Comment by peter1591** [comment]
Paper for AlphaGo Zero.

https://www.nature.com/articles/nature24270.epdf?author_access_token=VJXbVjaSHxFoctQQ4p2k4tRgN0jAjWel9jnR3ZoTv0PVW4gB86EEpGqTRDtpIz-2rmo8-KG06gqVobU5NSCFeHILHcVFUeMsbvwS-lxjqQGg98faovwjxeTUgZAUMnRQ

**Comment by wonderkid27** [comment]
I see your default policy and I think it just makes AI faster, not stronger. If we want AI grow stronger, we must use Reinforcement Learning.
