### ISSUE TITLE
Default policy

### ISSUE THREAD

**Issue by wonderkid27** [peter1591/hearthstone-ai#81]
After I train default policy neural network, I have a simulation_net file. How can I use it when I use VS to build project?

**Comment by wonderkid27** [comment]
May be edit include/MCTS/Config.h and build it again? But when I build completely, how can I run it and where do I put my simulation_net file?

**Comment by peter1591** [comment]
Yes, modify the config header, and rebuild.
Just put the 'simulation_net' file aside to the executable, it finds the file from current directory.
