### ISSUE TITLE
Why minions always attack face?

### ISSUE THREAD

**Issue by qj739** [peter1591/hearthstone-ai#83]
I watched the demo, the minions always attack enemy's face , but do not do minion exchange. 
when there is a buff card in hand , the AI use buff, after the minion attack , this lead to less of damage

**Comment by peter1591** [comment]
It depends on the Monte Carlo tree search. The tree search might not be deep enough due to limited computation power. And, the neural network itself cannot yet precisely predict a winning or losing. There are just too many to be improved. This is why I created this project. Let us keeping on it!
