### ISSUE TITLE
Binaries

### ISSUE THREAD

**Issue by wmlabtx** [peter1591/hearthstone-ai#87]
I appreciate your concern, Peter! Are you going to publish binaries? I have been trying to compile sources, but I couldn't.

C1083 Cannot open include file: 'UI/GameEngine.h': No such file or directory GameEngineCppCLI	d:\users\murad\hearthstone ai\trunk\ui\build\vs2017\gameenginecppcli\Header.h	3

**Comment by peter1591** [comment]
will do it after a trained neural network is released.
