### ISSUE TITLE
contact email

### ISSUE THREAD

**Issue by manuel-delverme** [peter1591/hearthstone-ai#98]
Hey Peter!
is there a way to contact you by email? 

Our approaches to the problem look similar and it seems to me that we arrived to the same conclusions (card2vec is vital) so working together could benefit both of us.

if you don't want to publish your address you can find mine here: manuel.delverme.it

**Comment by peter1591** [comment]
You should be able to find my email on my profile page. Anyway,
peter159.tw@gmail.com.
